# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: employees-web
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jmx:
  enabled : false       
      